#
# This is a hello world HOT template just defining a single compute
# server.
#
heat_template_version: 2013-05-23

description: >
  Hello world HOT template that just defines a single server.
  Contains just base features to verify base HOT support.

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    default: key-TP1
    
  flavor:
    type: string
    description: Flavor for the server to be created
    default: INF4410-mini
      
  network:
    type: string
    description: Network to connect
    default: 938775f1-1d27-4d35-a41d-e76eac6797db
    
  floating_network:
    type: string
    description: Network IP of external network
    default: 0c3b1354-d3d5-4fec-86d3-19d4d1f13785
      
  image:
    type: string
    description: Image ID or image name to use for the server
    default: INF4410-Ubuntu-trusty-mini
    
  instance_name:
    type: string
    description: Name of the instance
    default: serveur_python
   

resources:
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: floating_network }

  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks: 
        - network: { get_param: network }
      name: { get_param: instance_name }
      
      user_data: |
        #!/bin/bash
        wget https://raw.githubusercontent.com/houssemmh/INF8480-TP3/master/server.py
        exec python server.py
      
  floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: server }

outputs:
  server_networks:
    description: The networks of the deployed server
    value: { get_attr: [server, networks] }
